---
- name: Register if replicaset setup was previously completed, per node
  hosts: replicas
  tasks:
  - stat: 
      path: /opt/replicaset-setup-done
    register: replicaset_setup_done_stat

- name: Transcribe the above
  hosts: replicas
  tasks:
  - set_fact:
      replicaset_setup_done: "{{ replicaset_setup_done_stat.stat.exists }}"

- name: Determine if replicaset needs to be initialized
  hosts: replicaset_initializer
  tasks:
  - set_fact:
      previously_setup: "{{ groups['replicas'] | map('extract', hostvars, 'replicaset_setup_done') | list }}"

- name: Flag the machine that will initialize the replicaset
  hosts: replicaset_initializer
  tasks:
  - file:
      path: /opt/replicaset-initializer
      owner: root
      group: root
      mode: '0444'
      state: touch
    #There is probably a more elegant way to do this, but reduce filters seem rather limited in ansible
    when: true not in previously_setup